import { createTemplate, listTemplates } from './jsxgraph-templates.js';
import { mountJsxGraph, validateJsxGraphPayload } from './jsxgraph-renderer.js';
import { mountTable, typesetTableMath, validateTablePayload } from './table-renderer.js';
import { ensureChartJs, mountChart, validateChartPayload } from './chart-renderer.js';
import { createChartTemplate, listChartTemplates } from './chart-templates.js';

const $ = (id) => document.getElementById(id);
const INFO = {
  function_graph:['2D 함수·대수','기본 함수 그래프 (포물선)'],function_comparison:['2D 함수·대수','두 함수 비교 (포물선·직선)'],region_between_curves:['Calculus · 적분','두 곡선 사이 넓이'],piecewise:['2D 함수·대수','조각함수와 열린·닫힌 점'],tangent_and_secant:['Calculus · 미분','접선과 할선'],coordinate_polygon:['2D 기하·좌표','좌표평면 사각형'],circle_geometry:['2D 기하·좌표','원과 반지름'],inequality_region:['2D 함수·대수','연립일차부등식 음영'],calculus_integral_area:['Calculus · 적분','정적분 넓이'],calculus_riemann_sum:['Calculus · 적분','리만합 직사각형'],calculus_tangent_secant:['Calculus · 미분','접선·할선 비교'],calculus_parametric:['Calculus · 특수 곡선','매개변수 타원 곡선'],calculus_polar:['Calculus · 특수 곡선','극좌표 네잎장미'],calculus_accumulation:['Calculus · 적분','누적함수·FTC'],calculus_trigonometric:['Calculus · 특수 곡선','사인·코사인 그래프'],calculus_exponential_log:['2D 함수·대수','지수·로그 그래프'],calculus_rational_asymptote:['Calculus · 미분','유리함수와 점근선'],calculus_limit_hole:['Calculus · 미분','극한과 removable hole'],calculus_derivative_pair:['Calculus · 미분','f와 f′ 비교'],calculus_ellipse_parametric:['Calculus · 특수 곡선','매개변수 타원'],geometry_unit_circle:['2D 기하·좌표','단위원과 각도'],geometry_vector_components:['2D 기하·좌표','벡터와 성분'],calculus_absolute_value:['2D 함수·대수','절댓값 그래프와 꼭짓점'],calculus_cubic_inflection:['Calculus · 미분','삼차함수 변곡점'],calculus_logistic:['Calculus · 특수 곡선','로지스틱 성장 곡선'],calculus_inverse_trig:['Calculus · 특수 곡선','아크탄젠트와 점근선'],calculus_discontinuity:['Calculus · 미분','점프 불연속'],calculus_cardioid:['Calculus · 특수 곡선','극좌표 카디오이드'],calculus_spiral:['Calculus · 특수 곡선','극좌표 나선'],geometry_parabola_focus:['2D 기하·좌표','포물선·초점·준선'],geometry_concentric_circles:['2D 기하·좌표','동심원과 고리 영역'],geometry_triangle_altitude:['2D 기하·좌표','삼각형 높이'],three3d_coordinate_projection:['3D 좌표·벡터','좌표점과 정사영'],three3d_rectangular_prism:['3D 공간도형','직육면체'],three3d_cylinder:['3D 공간도형','원기둥·회전체'],three3d_cone:['3D 공간도형','원뿔'],three3d_plane_face:['3D 좌표·벡터','평면과 삼각형 면'],three3d_tetrahedron:['3D 공간도형','사면체'],three3d_two_planes:['3D 좌표·벡터','두 평면의 교선'],three3d_vector:['3D 좌표·벡터','벡터와 성분 분해'],three3d_sphere:['3D 공간도형','구와 반지름'],three3d_square_pyramid:['3D 공간도형','사각뿔'],three3d_line_and_plane:['3D 좌표·벡터','직선과 평면의 교점']
};
const templates = [...listTemplates().map(t => ({ id:t.id, category:(INFO[t.id] || ['Other'])[0], label:(INFO[t.id] || [null,t.label])[1] })), ...listChartTemplates()];
function createAnyTemplate(id){ return createChartTemplate(id) || createTemplate(id); }
let three;
function status(message, kind='info'){ $('jsonStatus').className='status '+kind; $('jsonStatus').textContent=message; }
function issues(result){ $('issues').innerHTML=[...(result.errors||[]),...(result.warnings||[])].map(x=>`<li><code>${x.code||'WARNING'}</code> ${x.path?`<strong>${x.path}</strong> — `:''}${x.message||''}</li>`).join(''); }
function parse(){ try{return {value:JSON.parse($('jsonInput').value)}}catch(error){return {error}} }
function fillTemplateSelect(){ const category=$('categorySelect').value; $('templateSelect').innerHTML='<option value="">Choose a ready template…</option>'+templates.filter(t=>category==='all'||t.category===category).map(t=>`<option value="${t.id}">${t.label}</option>`).join(''); }
function initTemplates(){ const categories=[...new Set(templates.map(t=>t.category))].sort(); $('categorySelect').innerHTML='<option value="all">All categories</option>'+categories.map(c=>`<option value="${c}">${c}</option>`).join(''); fillTemplateSelect(); }
async function render(){ const parsed=parse(); const host=$('viewerHost'); if(parsed.error){host.innerHTML='';issues({errors:[{code:'JSON_PARSE_ERROR',message:parsed.error.message}]});status('JSON syntax error.','error');return;} const engine=String(parsed.value.engine||'').toLowerCase(); if(engine==='three3d'){try{three ||= await import('./g3scene.js'); const check=three.validateThree3dPayload(parsed.value);issues(check);if(!check.valid){host.innerHTML='';status('Validation failed.','error');return;}three.mountThree3d(host,parsed.value);status('READY — Three.js 3D rendered. Drag to rotate; use the wheel to zoom.','success');}catch(error){host.innerHTML='';issues({errors:[{code:'THREE3D_RENDER_FAILED',message:error.message}]});status('3D renderer could not be loaded.','error');}return;} if(engine==='table'){const check=validateTablePayload(parsed.value);issues(check);if(!check.valid){host.innerHTML='';status('Validation failed.','error');return;}if(!mountTable(host,parsed.value)){host.innerHTML='';status('Table could not be rendered.','error');return;}await typesetTableMath(host);status('READY — Table rendered.','success');return;} if(engine==='chart'){try{const check=validateChartPayload(parsed.value);issues(check);if(!check.valid){host.innerHTML='';status('Validation failed.','error');return;}await ensureChartJs();if(!mountChart(host,parsed.value)){host.innerHTML='';status('Chart could not be rendered.','error');return;}status('READY — Chart.js rendered.','success');}catch(error){host.innerHTML='';issues({errors:[{code:'CHART_RENDER_FAILED',message:error.message}]});status('Chart renderer could not be loaded.','error');}return;} const check=validateJsxGraphPayload(parsed.value);issues(check);if(!check.valid){host.innerHTML='';status('Validation failed.','error');return;} if(!mountJsxGraph(host,parsed.value)){host.innerHTML='';status('JSXGraph could not be loaded.','error');return;}status('READY — JSXGraph rendered.','success'); }
function loadImage(file){if(!file)return;const reader=new FileReader();reader.onload=()=>{$('imageStage').innerHTML='<img alt="Source image for visual review">';$('imageStage').querySelector('img').src=String(reader.result||'');};reader.readAsDataURL(file);}
$('imageInput').addEventListener('change',()=>loadImage($('imageInput').files?.[0]));window.addEventListener('paste',event=>{const item=[...(event.clipboardData?.items||[])].find(i=>String(i.type).startsWith('image/'));if(item){event.preventDefault();loadImage(item.getAsFile());}});$('clearImage').addEventListener('click',()=>{$('imageInput').value='';$('imageStage').innerHTML='<span class="muted">Paste a screenshot with Ctrl+V,<br>or choose a source image.</span>';});$('categorySelect').addEventListener('change',fillTemplateSelect);$('loadTemplate').addEventListener('click',()=>{const value=$('templateSelect').value;if(!value){status('Choose a template first.','warning');return;}$('jsonInput').value=JSON.stringify(createAnyTemplate(value),null,2);render();});$('renderJson').addEventListener('click',render);$('formatJson').addEventListener('click',()=>{const p=parse();if(p.error){status('Cannot format invalid JSON.','error');return;}$('jsonInput').value=JSON.stringify(p.value,null,2);render();});$('copyJson').addEventListener('click',async()=>{const p=parse();if(p.error){status('Cannot copy invalid JSON.','error');return;}try{await navigator.clipboard.writeText(JSON.stringify(p.value));status('Compact JSON copied.','success');}catch{status('Clipboard is unavailable; copy manually.','warning');}});initTemplates();render();
