import {createClient} from"npm:@supabase/supabase-js@2";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type","Content-Type":"application/json;charset=utf-8"};
const out=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:H});
const PRODUCTS=new Set(["realestate","insurance","mortgage","notary"]);
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return out({error:"Method not allowed"},405);
 const url=Deno.env.get("SUPABASE_URL")||"",service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!url||!service)return out({error:"Server configuration unavailable"},500);const admin=createClient(url,service,{auth:{persistSession:false}});const p=await req.json().catch(()=>({}));
 if(p.action==="catalog"){const{data,error}=await admin.from("license_products").select("product_code,title,sample_limit,set_size,license_questions(count)").eq("active",true).order("title");return error?out({error:error.message},500):out({products:data});}
 const product=String(p.product||"").toLowerCase();if(!PRODUCTS.has(product))return out({error:"Unknown license product"},400);
 let full=false,userId="";const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"");if(token){const{data}=await admin.auth.getUser(token);userId=data.user?.id||"";if(userId){const{data:profile}=await admin.from("member_profiles").select("account_type,active").eq("id",userId).maybeSingle();if(profile?.active&&profile.account_type==="admin")full=true;if(!full){const{data:e}=await admin.from("license_entitlements").select("status,starts_at,expires_at").eq("user_id",userId).eq("product_code",product).eq("status","active").maybeSingle();const now=new Date();full=!!e&&new Date(e.starts_at)<=now&&(!e.expires_at||new Date(e.expires_at)>=now);}}}
 const langs=Array.isArray(p.languages)?p.languages.map(String).filter((x:string)=>/^[a-z]{2,8}$/i.test(x)).slice(0,2):["en","ko"];let q=admin.from("license_questions").select("question_id,product_code,sequence_number,subject,category,answer,graphic,is_sample,sample_order,status,license_question_translations(language_code,question_text,passage_text,option_1,option_2,option_3,option_4,explanation)").eq("product_code",product).eq("status","published").in("license_question_translations.language_code",langs).order(full?"sequence_number":"sample_order");if(!full)q=q.eq("is_sample",true).limit(20);else q=q.limit(Math.min(200,Math.max(1,Number(p.limit)||100))).range(Math.max(0,Number(p.offset)||0),Math.max(0,Number(p.offset)||0)+Math.min(200,Math.max(1,Number(p.limit)||100))-1);const{data,error}=await q;return error?out({error:error.message},500):out({access:full?"full":"sample",product,data});});
